#! /bin/bash
#
# Copyright (c) 2019, AT&T Intellectual Property. All rights reserved.
# Copyright (c) 2014-2016 by Brocade Communications Systems, Inc.
# All rights reserved.
#
# SPDX-License-Identifier: GPL-2.0-only
#

source "$(cd "$(dirname "${0}")" && pwd -P)"/../tech-support.functions

header Routing Services Configuration
time_out "vtysh -c 'show run' "
